import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";

const antonio = localFont({
  src: [
    {
      path: './fonts/Antonio-Regular.woff2',
      weight: '400',
      style: 'normal',
    },
    {
      path: './fonts/Antonio-Bold.woff2',
      weight: '700',
      style: 'bold',
    }
  ],
  variable: '--font-lcars',
});

const firaCode = localFont({
  src: [
    {
      path: './fonts/FiraCode-Regular.woff2',
      weight: '400',
      style: 'normal',
    },
    {
      path: './fonts/FiraCode-Medium.woff2',
      weight: '500',
      style: 'medium',
    },
    {
      path: './fonts/FiraCode-Bold.woff2',
      weight: '700',
      style: 'bold',
    }
  ],
  variable: '--font-code',
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${firaCode.variable} ${antonio.variable} antialiased font-body bg-matrix-dark`}
      >
        {children}
      </body>
    </html>
  );
}
